Repository tectijuana/tallerdb, pull requests merged in 2025-02, with the labels that each got.

#15 33-Protege datos con CHECK en restricciones.md
  resources/tutorials/tips/33-Protege datos con CHECK en restricciones.md
Labels: good first issue

#12 13 - Usa RIGHT JOIN para mantener datos derechos.md
  13-Usa RIGHT JOIN para mantener datos derechos.md
Labels: invalid

#5 Tip 27 - Convierte valores con CAST y CONVERT
  resources/tutorials/tips/27-Convierte valores con CAST y CONVERT.md
Labels: good first issue

#4 Contribución de prompt 22-Usa OFFSET para paginación
  resources/tutorials/tips/22-Usa OFFSET para paginación.md
Labels: good first issue

#23 37- Usa REPLACE para actualizar filas
  resources/tutorials/tips/37- Usa REPLACE para actualizar o insertar filas.md
Labels: good first issue

#22 39-Encuentra valores extremos con MIN y MAX.md
  resources/tutorials/tips/39-Encuentra valores extremos con MIN y MAX.md
Labels: good first issue

#26 Listo la revision profe
  resources/tutorials/tips/5-8-Usa LAG() y LEAD() para comparar filas consecutivas.md-Implementa GROUPING SETS para resúmenes avanzados.md
Labels: documentation

#30 Create 10-Usa DISTINCT para eliminar duplicados.md
  resources/tutorials/tips/10-Usa DISTINCT para eliminar duplicados.md
Labels: good first issue

#29 28-Calcula fechas con DATEDIFF y DATEADD.md
  resources/tutorials/tips/28-Calcula fechas con DATEDIFF y DATEADD.md
Labels: invalid

#77 Create readme.md
  assignments/U1/sqlzoo.net/selectDeselect/Eduardoch12v/readme.md
Labels: good first issue

#67 Trabajo de clase SQLZOO mapamundi
  assignments/U1/sqlzoo.net/MapaMundi/Rother22/Readme.md
Labels: invalid

#98 JordhyRojas05- SelectDeselect
  39_Encuentra valores extremos con MIN y MAX.md
  assignments/U1/sqlzoo.net/MapaMundi/JordhyRojas05/readme.md
  assignments/U1/sqlzoo.net/selectDeselect/JordhyRojas05/readme.md
Labels: Comentarios
